### PR TITLE
Feature/meastro commands/unit tests/gh actions

### PR DESCRIPTION
**Pull request by irhlab49**
@shoma-mano

This PR introduces several key enhancements to the codebase, focusing on command refactoring, test coverage, and documentation updates. The changes aim to make command properties more flexible, improve test reliability, and provide clearer documentation for users.

Key Changes
1. Command Refactoring
Refactored existing command functions to improve readability, maintainability, and flexibility.
Introduced optional properties (Props) for commands, specifically for taps, waits, and other customizable actions. These optional properties (such as TapProps, WaitProps, and PointProps) allow for more control over the behavior of commands.

2. Unit Tests
- Added snapshot tests to capture and validate the output of each command, ensuring that any unintended changes are detected during development.
- Set up GitHub Actions to automatically run unit tests on all pull requests, enabling continuous testing and preventing potential issues from merging.

3. Documentation Updates
Updated the main README.md with details about the new optional command properties and provided example usages.
Added a separate commands.md file with a detailed breakdown of each command and its properties for easy reference and a deeper understanding of customization options.

Please review these changes and let me know if you have any questions or feedback. The added GitHub Actions for PRs will allow us to maintain quality with automated testing, making future changes easier to validate.

### CODE REVIEW

**Comment by irhlab49** [comment]
@shoma-mano  i'll fix the merge conflicts and do some testing locally

**Comment by shoma-mano** [comment]
@irhlab49 
Thanks so much for your contribution!🌟
It’s really helpful!

Here are the points I want to convey:
- Inline snapshots seem better than regular snapshots at the moment.
- I think writing commands as a string literal [like this](https://github.com/shoma-mano/maests/blob/a0f1a6ad5eb98a00810f1d0a8a77001689effcc4/src/commands.ts#L389C2-L392) is generally the most readable approach.
- I want to adopt an In-Source Testing style wherever possible [like this](https://github.com/shoma-mano/maests/blob/main/src/rewriteCode.ts). However, to do so, we need to break down the current single commands file.
- example folder has been deleted, and a playground folder has been created to actually execute tests using the simulator. 

The PR looks good to me overall, apart from a few points. I'll merge this early, and I'll try to make the necessary adjustments myself If there are still any concerns.

**Comment by irhlab49** [comment]
Thank you @shoma-mano . Do you need me to do any more in order to merge+release?

**Comment by irhlab49** [comment]
i'm just converting the tests to inline, will be done soon

**Comment by shoma-mano** [comment]
@irhlab49 

> i'm just converting the tests to inline, will be done soon

I will merge PR when you finish this!

**Comment by irhlab49** [comment]
@shoma-mano  done :) Please review and let me know if anything else is required

**Comment by shoma-mano** [comment]
@irhlab49 
It's a minor thing, but version up seems to be included release script
`changelogen --release  --publish --push`

**Comment by shoma-mano** [comment]
I want to add you to contributor list automatically, but I don't know why, it was not included automatically.
changelogen may only support  [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/).

**Comment by irhlab49** [comment]
I will give that a try for the next commit @shoma-mano. Thank you for merging!

**Pull request merged**
