### PR TITLE
Add support for "Wait for Element Before Tapping" command.

### PR DESCRIPTION
**Pull request by irhlab49**
@shoma-mano This PR introduces a new command to wait for an element to become visible or accessible before performing a tap action. This ensures that interactions with elements are stable and reduces the chances of flaky tests due to elements not being ready when a tap command is executed. 

I had an issue tapping on screens that contained skeleton loaders. 

Key Changes:
Implemented a new `waitForAndtapOn` command to handle element availability.

Let me know if you need more detail or specific adjustments!

### CODE REVIEW

**Comment by irhlab49** [comment]
@shoma-mano can you please review, release if you're OK with this?

**Comment by shoma-mano** [comment]
@irhlab49 
I'm not sure if using TypeScript for Maestro will work well, but thank you for your interest!
I'm grad if you will cooperate to grow this library!

I have merged your PR and published package for now!

**Comment by irhlab49** [comment]
I have some more ideas on how we can improve @shoma-mano . I will definitely contribute more, when time allows :)

**Comment by shoma-mano** [comment]
@irhlab49 
Thanks!!

**Pull request merged**
